[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
ethereumGoerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
